FORMAT: 1A
HOST: http://www.google.com

# Eve Stuff
Eve Stuff API gives access to my ship setups, blueprints and other completely useless eve stuff if you'r not into eve and if you'r not me. Trail project obviously.

# Group Notes
Ship and Ship setups: allows to view, add, modify, delete ships and ship-setups

## Ships Collection [/ships]
### List all ships for which i have setups [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "shipclass": "frigate", "shiptype": "Kestrel", "shipname": "Alpha"
        }, {
          "id": 2, "shipclass": "cruiser", "shiptype": "Caracal", "shipname": "Gamma"
        }]

### Create a ship [POST]
+ Request (application/json)

        { "shipclass": "battlecruiser", "shiptype": "Drake", "shipname": "Delta" }

+ Response 201 (application/json)

        { "id": 3, "shipclass": "battlecruiser", "shiptype": "Drake", "shipname": "Delta" }

## Ship [/ships/{id}]
Ship details and links to setups

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Ship to perform action with. Has example value.

### Retrieve a Ship [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
